### ISSUE TITLE
Day switching at 23:00 with Romme calculation method

### ISSUE THREAD

**Issue by PyvesB** [caarmen/french-revolutionary-calendar#18] opened 2018-03-31 14:41 UTC
Hello!

I just noticed that the calendar day seemed to switch at 23:00 with the Romme calculation method when using some timezones. For instance consider the following example:
```
FrenchRevolutionaryCalendar revolutionaryCalendar = new FrenchRevolutionaryCalendar(Locale.ENGLISH, CalculationMethod.ROMME);
ZoneId paris = ZoneId.of("Europe/Paris");
GregorianCalendar cal1 = GregorianCalendar.from(ZonedDateTime.of(2018, 1, 28, 22, 59, 0, 0, paris));
GregorianCalendar cal2 = GregorianCalendar.from(ZonedDateTime.of(2018, 1, 28, 23, 0, 0, 0, paris));
System.out.println(revolutionaryCalendar.getDate(cal1).dayOfMonth);
System.out.println(revolutionaryCalendar.getDate(cal2).dayOfMonth);
```

The first log line will output 9, the second log line will output 10, which doesn't seem correct. Some other zone ids suffer from the same issue (for instance `US/Michigan`), some others don't (for instance `Africa/Tunis`).

Cheers,

Pyves

**Comment by caarmen** [comment] 2018-04-01 10:55
I've created branch issue-18 for this.

I've added a unit test for this exact scenario :) 

Did a similar fix as the #17 bug fix: using utc for calculations instead of dst offsets.

Tested in London, Paris, Tunis, Lansing and some other time zones.

**Comment by caarmen** [comment] 2018-04-01 11:11
Fixed in version 1.8.1.

**Closed by caarmen** 2018-04-01 11:11 UTC

**Comment by PyvesB** [comment] 2018-04-01 11:27
Thanks for fixing this!

**Comment by caarmen** [comment] 2018-04-01 11:35
Thanks for the very detailed and specific report. Made it easy to reproduce the issue :)

BTW, this isn't on jcenter yet, because the bintray website is having issues. I can't upload the release there right now.

**Comment by PyvesB** [comment] 2018-04-01 12:11
No worries, there's no rush! 😄

**Comment by PyvesB** [comment] 2018-04-19 21:11
@caarmen : this is not related to this issue, but I just wanted to give you a shout about a project that I've made with the help of your library. It's an Alexa skill that allows users to convert dates using the french revolutionary calendar. It's available on my GitHub [here](https://github.com/PyvesB/alexa-revolutionary-calendar). You should try it out if you manage to get hold of an Alexa device! 😉
